#define LWIP_TCPIP_CORE_LOCKING 1
#define LWIP_SUPPORT_CUSTOM_PBUF 1
#define LWIP_NETIF_LOOPBACK 1
#define LWIP_HAVE_SLIPIF 0
#define LWIP_NETIF_API 1
#define LWIP_SOCKET 1
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_ARP 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_AUTOIP 0
#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_TCP_KEEPALIVE 1
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define LWIP_ERRNO_INCLUDE <errno.h>
#define LWIP_DNS_API_DEFINE_ERRORS 0
#define LWIP_DNS_API_DEFINE_FLAGS 0
#define LWIP_DNS_API_DECLARE_STRUCTS 0
#define LWIP_DNS_API_DECLARE_H_ERRNO 0
#define MEMP_NUM_NETCONN 1024

#define TCP_MSS 1460
#define TCP_WND (32 * TCP_MSS)
#define TCP_SND_BUF TCP_WND
#define ETH_PAD_SIZE 0
#define ETHARP_TABLE_MATCH_NETIF 1
#define IP_REASSEMBLY 1
#define IP_FRAG 1
#define SO_REUSE 1
#define DEFAULT_THREAD_STACKSIZE (4 * 4096)
#define TCPIP_THREAD_STACKSIZE (4 * 4096)
#define TCPIP_THREAD_PRIO 3
#define TCPIP_MBOX_SIZE 256
#define DEFAULT_RAW_RECVMBOX_SIZE 32
#define DEFAULT_UDP_RECVMBOX_SIZE 32
#define DEFAULT_TCP_RECVMBOX_SIZE 32
#define DEFAULT_ACCEPTMBOX_SIZE 32

#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_DHCP_AUTOIP_COOP 0
#define LWIP_DHCP_AUTOIP_COOP_TRIES 3
#define LWIP_SO_RCVTIMEO 1

#ifndef LWIP_SOCKET_OFFSET
#define LWIP_SOCKET_OFFSET 0
#endif

#ifdef FD_SETSIZE
#undef FD_SETSIZE
#endif
#define FD_SETSIZE 16

#define LWIP_SOCKET_EXTERNAL_HEADERS 1
#define LWIP_SOCKET_EXTERNAL_HEADER_SOCKETS_H "sys/socket.h"
#define LWIP_SOCKET_EXTERNAL_HEADER_POLL_H "arch/cc.h"
#define LWIP_SOCKET_EXTERNAL_HEADER_INET_H "arch/cc.h"
#define LWIP_SOCKET_EXTERNAL_HEADER_NETDB_H "arch/cc.h"
#define LWIP_SOCKET_HAVE_SA_LEN 1
#define LWIP_SELECT_MAXNFDS 16
#define LWIP_ACD 0
#define LWIP_DHCP_DOES_ACD_CHECK 0
#define DHCP_DOES_ARP_CHECK 0

#define LWIP_DEBUG 1
#define DHCP_DEBUG LWIP_DBG_ON
#define UDP_DEBUG LWIP_DBG_ON
#define ETHARP_DEBUG LWIP_DBG_ON
#define NETIF_DEBUG LWIP_DBG_ON
#define IP_DEBUG LWIP_DBG_ON
