
SRCS-$(CONFIG_RAMDISK)+=	dev/block/ramdisk.c
SRCS-$(CONFIG_FDD)+=		dev/block/fdd.c
SRCS-$(CONFIG_SDMMC)+=		dev/block/sdmmc.c
SRCS-$(CONFIG_PL181)+=		dev/block/pl181.c
SRCS-$(CONFIG_BCM2835_SD)+=	dev/block/bcm2835_sd.c
