/*
 * exec_globals.c - PIC-safe global variables and getter functions
 *
 * DESIGN RATIONALE FOR KEEPING THESE GLOBALS AND HELPERS IN C:
 *
 * 1. NOMMU XIP (Execute-in-Place) Global State Safety:
 *    On NOMMU targets (like arm-musca-b1 or arm-integrator), the exec server's
 *    code segment (.text) runs directly from read-only Flash, while its data
 *    (.data/.bss) is loaded into SRAM.
 *    If Zig references a global variable directly under non-PIC/non-PIE models,
 *    it generates absolute relocations (e.g. R_ARM_ABS32) inside the Flash
 *    segment. Since Flash is read-only at runtime, these relocations cannot be
 *    patched, causing immediate hardware faults.
 *    Defining globals in C (compiled using GCC with -fpic -msingle-pic-base
 *    -mpic-register=r9) allows safe access via GOT (R9 register). Zig accesses
 *    them via getter/setter functions, generating PC-relative 'bl' calls.
 *
 * 2. Stack Alignment and Pointer Manipulation (build_args):
 *    build_args performs low-level stack setup, pointer casting, and alignment
 *    requirements (e.g. 16-byte alignment on RISC-V) for newly spawned tasks.
 *    Keeping this logic in C avoids pointer-coercion warnings in Zig and guarantees
 *    the stack matches the exact layout assumed by Prex crt0.o assembly.
 *
 * 3. Dynamic Header Inclusions (conf/captab.h):
 *    The capability table is generated during build configuration (captab.h).
 *    Centralizing its inclusion in C avoids polluting the Zig @cInclude namespace.
 */

#include <sys/types.h>
#include <sys/param.h>
#include <sys/prex.h>
#include <sys/capability.h>
#include <ipc/exec.h>
#include <ipc/ipc.h>
#include <ipc/fs.h>
#include <ipc/proc.h>
#include <sys/elf.h>
#include <sys/list.h>

#include <limits.h>
#include <string.h>
#include <errno.h>

#include "exec.h"

/* External handler declarations (exported from Zig) */
extern int exec_execve(struct exec_msg*);
extern int exec_bindcap(struct bind_msg*);
extern int exec_boot(struct msg*);
extern int exec_shutdown(struct msg*);
extern int exec_debug(struct msg*);
extern int exec_null(struct msg*);

/* ===== Static variables ===== */

/* Buffer for reading file headers (exec_execve.c) */
static char hdrbuf[HEADER_SIZE];

/* Section addresses for ELF relocation on non-MMU (exec_elf.c) */
char* sect_addr[32];

#ifdef __arm__
Elf32_Addr sram_got_base;
#endif
Elf32_Half elf_type;
Elf32_Addr text_vma;
Elf32_Addr data_vma;
Elf32_Addr text_runtime;
Elf32_Addr data_runtime;
Elf32_Sym* current_symtab;

/* Script interpreter buffers (exec_script.c) */
static char interp[PATH_MAX];
static char intarg[LINE_MAX];
static char script[LINE_MAX];

/* Loader table (from exec_conf.c) */
extern void elf_init(void);
extern int elf_probe(struct exec*);
extern int elf_load(struct exec*);

extern void script_init(void);
extern int script_probe(struct exec*);
extern int script_load(struct exec*);

struct exec_loader loader_table[] = {
    {"elf", elf_init, elf_probe, elf_load},
    {"script", script_init, script_probe, script_load},
};

const int nloader = (int)(sizeof(loader_table) / sizeof(loader_table[0]));

/* Include the capability table generated by configure script */
#include <conf/captab.h>

/* ===== PIC-safe getter functions ===== */

char* hdrbuf_get(void) { return hdrbuf; }

void hdrbuf_zero(void) { memset(hdrbuf, 0, HEADER_SIZE); }

char** sect_addr_get(void) { return sect_addr; }

Elf32_Half get_elf_type(void) { return elf_type; }

Elf32_Addr get_text_vma(void) { return text_vma; }

Elf32_Addr get_data_vma(void) { return data_vma; }

Elf32_Addr get_text_runtime(void) { return text_runtime; }

Elf32_Addr get_data_runtime(void) { return data_runtime; }

void set_elf_type(Elf32_Half val) { elf_type = val; }

void set_text_vma(Elf32_Addr val) { text_vma = val; }

void set_data_vma(Elf32_Addr val) { data_vma = val; }

void set_text_runtime(Elf32_Addr val) { text_runtime = val; }

void set_data_runtime(Elf32_Addr val) { data_runtime = val; }

#ifdef __arm__
void set_sram_got_base(Elf32_Addr val) { sram_got_base = val; }
#endif

void set_current_symtab(Elf32_Sym* symtab) { current_symtab = symtab; }

char* get_script_interp(void) { return interp; }

char* get_script_intarg(void) { return intarg; }

char* get_script_name(void) { return script; }

struct exec_loader* loader_table_get(void) { return loader_table; }

int nloader_get(void) { return nloader; }

const struct cap_map* cap_table_get(void) { return cap_table; }

/* ===== String getters for NOMMU XIP safety ===== */

const char* get_boot_msg(void) { return "Starting exec server\n"; }

const char* get_no_proc_msg(void) { return "exec: no proc found"; }

const char* get_create_obj_fail_msg(void) { return "exec: fail to create object"; }

const char* get_exec_obj_name(void) { return "!exec"; }

const char* get_proc_obj_name(void) { return "!proc"; }

const char* get_exec_path(void) { return "/boot/exec"; }

const char* get_fs_obj_name(void) { return "!fs"; }

const char* get_cmdbox_path(void) { return "/boot/cmdbox"; }

const char* get_sh_bin(void) { return "sh"; }

/* ===== Exception handler ===== */

static void exception_handler(int sig)
{
    exception_return();
}

void setup_exec_exception(void)
{
    exception_setup(exception_handler);
}

/* ===== build_args (ported from C to bypass Zig compiler issues) ===== */

#include <sys/stat.h>
#include <ipc/exec.h>
#include <ipc/proc.h>
#include <ipc/fs.h>
#include <ipc/ipc.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

extern int exec_execve(struct exec_msg*);

#ifdef __riscv__
#define SP_ALIGN(p) ((unsigned)(p) & ~15)
#else
#define SP_ALIGN(p) ((unsigned)(p) & ~_ALIGNBYTES)
#endif

int build_args(task_t task, void* stack, char* path, struct exec_msg* msg,
               char* xarg1, char* xarg2, void** new_sp);

int build_args(task_t task, void* stack, char* path, struct exec_msg* msg,
               char* xarg1, char* xarg2, void** new_sp)
{
    int argc, envc;
    char* file;
    char **argv, **envp;
    int i, error;
    u_long arg_top, mapped, sp;
    int len;

    argc = msg->argc;
    envc = msg->envc;

    error = vm_map(task, stack, DFLSTKSZ, (void*)&mapped);
    if (error)
        return ENOMEM;
    memset((void*)mapped, 0, DFLSTKSZ);
    sp = mapped + DFLSTKSZ - sizeof(int) * 3;

    /* Copy items */
    *(char*)sp = '\0';
    sp -= strlen(path);
    sp = SP_ALIGN(sp);
    strlcpy((char*)sp, path, PATH_MAX);
    file = (char*)sp;

    sp -= msg->bufsz;
    sp = SP_ALIGN(sp);
    memcpy((char*)sp, (char*)&msg->buf, msg->bufsz);
    arg_top = sp;

    if (xarg2 != NULL) {
        len = strlen(xarg2);
        sp -= (len + 1);
        strlcpy((char*)sp, xarg2, len + 1);
        arg_top = sp;
        argc++;
    }
    if (xarg1 != NULL) {
        len = strlen(xarg1);
        sp -= (len + 1);
        strlcpy((char*)sp, xarg1, len + 1);
        arg_top = sp;
        argc++;
    }

#ifdef __riscv__
    /* RISC-V layout: argc | argv[0..argc+1] | envp[0..envc] */
    len = sizeof(int) + (argc + 2) * sizeof(char*) + (envc + 1) * sizeof(char*);
    sp = SP_ALIGN(sp - len);

    *(int*)sp = argc + 1;
    argv = (char**)(sp + sizeof(int));
    envp = (char**)(sp + sizeof(int) + (argc + 2) * sizeof(char*));
#else
    /* envp[] */
    sp -= ((envc + 1) * sizeof(char*));
    envp = (char**)sp;

    /* argv[] */
    sp -= ((argc + 1) * sizeof(char*));
    argv = (char**)sp;

    /* argc */
    sp -= sizeof(int);
    *(int*)(sp) = argc + 1;
#endif

    /* Build argument list */
    argv[0] = (char*)((u_long)stack + (u_long)file - mapped);

    for (i = 1; i <= argc; i++) {
        argv[i] = (char*)((u_long)stack + (arg_top - mapped));
        while ((*(char*)arg_top++) != '\0')
            ;
    }
    argv[argc + 1] = NULL;

    for (i = 0; i < envc; i++) {
        envp[i] = (char*)((u_long)stack + (arg_top - mapped));
        while ((*(char*)arg_top++) != '\0')
            ;
    }
    envp[envc] = NULL;

    *new_sp = (void*)((u_long)stack + (sp - mapped));
    vm_free(task_self(), (void*)mapped);
    return 0;
}

/* ===== Message dispatch ===== */

int dispatch_msg(int code, struct msg* msg)
{
    if (code == EXEC_EXECVE)
        return exec_execve((struct exec_msg*)msg);
    else if (code == EXEC_BINDCAP)
        return exec_bindcap((struct bind_msg*)msg);
    else if (code == STD_BOOT)
        return exec_boot(msg);
    else if (code == STD_SHUTDOWN)
        return exec_shutdown(msg);
    else if (code == STD_DEBUG)
        return exec_debug(msg);
    else
        return exec_null(msg);
}
